### ISSUE TITLE
Github Actions needs repository activity to run

### ISSUE THREAD

**Issue by guilhermepaula** [patlux/expo-cli-docker-images#1]
Hello,

The last time github actions were performed was 10 days ago. There's a warning on the page: "This scheduled workflow is disabled because there hasn't been activity in this repository for at least 60 days".

I think a simple commit is necessary to solve for the next 60 days.

Thanks

**Comment by patlux** [comment]
Hi,

you're right. I just ignored all warning emails successfully ;)

It's now enabled again.

Thanks for the reminder!
